name: flutter_module_sample
description: Main modular flutter app
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.2.0
  web: ^1.1.0

  dummy_flutter_module:
    git:
      url: https://github.com/tushardubey121/dummy_flutter_module.git

flutter:
  uses-material-design: true
